name: Build Windows Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed facturacion_app.spec
      
    - name: Create ZIP archive
      run: |
        mkdir -p output
        
        if (Test-Path "dist/Sistema de Facturacion.exe") {
          Copy-Item "dist/Sistema de Facturacion.exe" -Destination "output/"
          Compress-Archive -Path "output/*" -DestinationPath "Sistema_de_Facturacion_Windows.zip"
        } else {
          Write-Error "No se encontró el ejecutable. Verificando el contenido del directorio dist:"
          dir dist
          exit 1
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: Sistema_de_Facturacion_Windows.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Sistema_de_Facturacion_Windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}